project:
  type: website
  output-dir: docs

website:
  title: "Analyse quantitative - M1 Villes et environnements urbains"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Seance_1.qmd
      - Seance_2.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



