project:
  type: website
  output-dir: docs

website:
  title: "Analyse quantitative - M2 Villes et environnements urbains"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Seance1.qmd
      - Seance2.qmd
      - pptS2.qmd
      - rappel_S1S2.qmd
      - Seance3.qmd
      - pptS4.qmd
      - DM_corrige_code.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



